# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-context" do
  version "0.0.5-SNAPSHOT-3a55a87"

  on_macos do
    on_intel do
      sha256 "ad1b402e6f5b92aa730ab5e39c91e308cfba83076fb71d3e19f285719d1089cc"
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.0.5/project-context_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ecd5bf54e2d40eea52ff55ca76216a107e13adce667ec251803a80ac46d755bd"
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.0.5/project-context_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7547f0069531f84a197522ff51279edb1002336f2d664e6e201f6e5896a50928"
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.0.5/project-context_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a0920bd9fb29a1dc4e832a2a6a467d915b373ea0486f1d7f57055e2d7dc2461"
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.0.5/project-context_#{version}_linux_arm64.tar.gz"
    end
  end

  name "project-context"
  desc "Zero-dependency CLI that generates a perfect project-context.md for LLMs, code reviews, or documentation."
  homepage "https://github.com/pixeljuggle/project-context"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-context"

  # No zap stanza required

end
