# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-context" do
  version "0.0.7"

  on_macos do
    on_intel do
      sha256 "fb0dfdc66bc310fb945bfe5e22f66a0bd04c32bd06568ab921210cda2a5a6d90"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba7b27f8266876d142dcf54cd4a69b137662a57b0cfedaee5a9325c555561a6f"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd1accaa71592c4941b59ad33bbd8135322de26d962db8da6e610a3622ab0bb2"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "40759404a6f7899afe1e73780af7747b6e9ed57b8780c594ec6a008b2fcf0be5"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_linux_arm64.tar.gz"
    end
  end

  name "project-context"
  desc "Zero-dependency CLI that generates a perfect project-context.md for LLMs, code reviews, or documentation."
  homepage "https://github.com/pixeljuggle/project-context"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-context"

  # No zap stanza required

end
