# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-context" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "c77484b841632356f99eebc38dfe1d60db3043a0b53e4cc751d7368222546e9f"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a08b35e6f572fdf6d72f24f47b01a7adb2e6841d692882ba95fdad366ac08f3"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f5769d9c2d79e360016e0dafa4ae423b7e7c2e564659d768403df4dda37453b9"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b552c9c81e6eef6d56250536eb8c6577464b56c4ae7f76c8e6399e72061c7ed0"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_linux_arm64.tar.gz"
    end
  end

  name "project-context"
  desc "Zero-dependency CLI that generates a perfect project-context.md for LLMs, code reviews, or documentation."
  homepage "https://github.com/pixeljuggle/project-context"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-context"

  # No zap stanza required

end
