# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProjectContext < Formula
  desc "Zero-dependency CLI that generates a perfect project-context.md for LLMs, code reviews, or documentation."
  homepage "https://github.com/pixeljuggle/project-context"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.1.5/project-context_0.1.5_darwin_amd64.tar.gz"
      sha256 "7ea3f9aff8fda43f060958381c8989a4e39432b9c474244aa4c50195fdb1c518"

      define_method(:install) do
        bin.install "project-context"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.1.5/project-context_0.1.5_darwin_arm64.tar.gz"
      sha256 "cc56e33d13ff55bd5be7b126075a2e09684d12a82574e5eedb5883961f02f08c"

      define_method(:install) do
        bin.install "project-context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.1.5/project-context_0.1.5_linux_amd64.tar.gz"
      sha256 "50fe52f3728ad97b3434932c84aebe0376496000fbf28093d15f9e3f5989ead1"
      define_method(:install) do
        bin.install "project-context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.1.5/project-context_0.1.5_linux_arm64.tar.gz"
      sha256 "a973cd0bf212859cac47533f38f1467975c0f1044f06581a724f870173a6a001"
      define_method(:install) do
        bin.install "project-context"
      end
    end
  end

  test do
    system "#{bin}/project-context --version"
  end
end
