# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProjectContext < Formula
  desc "Zero-dependency CLI that generates a perfect project-context.md for LLMs, code reviews, or documentation."
  homepage "https://github.com/pixeljuggle/project-context"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.0.10/project-context_0.0.10_darwin_amd64.tar.gz"
      sha256 "56edbda9a723fd7068e08c242e24201fd9b5eebaecb992cbd162555a36e7935d"

      define_method(:install) do
        bin.install "project-context"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.0.10/project-context_0.0.10_darwin_arm64.tar.gz"
      sha256 "affaeb15a0f0b7af2c5e188310e1a0250ef28d8e804e7fc1def003e9703b5b58"

      define_method(:install) do
        bin.install "project-context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.0.10/project-context_0.0.10_linux_amd64.tar.gz"
      sha256 "dadf3ba8a34a821d3e283c848644d5873ccd64a9bcb407a8e06934c4fd9df75d"
      define_method(:install) do
        bin.install "project-context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixeljuggle/project-context/releases/download/v0.0.10/project-context_0.0.10_linux_arm64.tar.gz"
      sha256 "10134013003b7e60523abcf594347b5e3ea729ccfcaebb01f5e404157b457cfe"
      define_method(:install) do
        bin.install "project-context"
      end
    end
  end

  test do
    system "#{bin}/project-context --version"
  end
end
