# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-context" do
  version "0.0.9"

  on_macos do
    on_intel do
      sha256 "9ac708713d69d5186f25f08033902ecfefc2d4f414b7675276270dd129d53fd9"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c2c4346c5e61e92c6da78ffc74ca8b60cf314e4af566f261367b727f58941eda"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "14148f0be5af21f9f8d8fa4118134780c331c898a56abb192178b1b4c910d8b5"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29a014d309cf37dfed5970fe10b472a179450c48b68fa7c2bcae4724009b3106"
      url "https://github.com/pixeljuggle/project-context/releases/download/v#{version}/project-context_#{version}_linux_arm64.tar.gz"
    end
  end

  name "project-context"
  desc "Zero-dependency CLI that generates a perfect project-context.md for LLMs, code reviews, or documentation."
  homepage "https://github.com/pixeljuggle/project-context"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-context"

  # No zap stanza required

end
